(* ::Package:: *)


ExtractCode::usage = "ExtractCode[ifname, output, \"force\"->(True|False)] -- extract \
input and code cells from the notebook and save it to separate code file. Option \"force\" \
forces overwrite of the file"


ExtractCode::help = "
DESCRIPTION:
  ifname -- notebook file name (String)
  output -- output file name (default = Null means save notebook contents to the file with changed \
extension to wl)
  '-force' -- force overwriting of the output file
EXAMPLES:
  math -script ExtractCode.wl notebook.nb code.wl
  math -script ExtractCode.wl notebook.nb -o path
  math -script ExtractCode.wl notebook.nb -o path/code.wl
  math -script ExtractCode.wl notebook.nb
  math -script ExtractCode.wl notebook.nb -force
"

ExtractCode::exist = "file '``' does exist, use '-force' flag to overwrite\n"
getHash[fname_String, nMax_:5] := Module[{s, n=0, hash=$Failed},
  With[{f = OpenRead[fname]},
    While[((s = ReadLine[f]) =!= EndOfFile) && ((n += 1) < nMax),
      If[StringStartsQ[s, "(* [hash]: "], hash = ToExpression[StringTake[s, {11, -3}]];];
    ];
    Close[f];
  ];
  Return[hash];
];

Options[ExtractCode] = {"force"->False};
ExtractCode[ifname_, output:(Null|_String), opts:OptionsPattern[]] := Module[{
  data,
  ofname = output,
  force = OptionValue["force"],
  headerTemplate = "(* [info]: this file is autogenerated from the notebook '``' *)\n",
  dateTemplate = "(* [date]: `` *)\n",
  hashTemplate = "(* [hash]: `` *)\n\n\n",
  hash
},
If[Not@FileExistsQ[ifname], (
  Message[General::notfound, ifname];
  Return[$Failed];
)];
ofname = Which[
  output === Null, FileBaseName[ifname]<>".wl",
  DirectoryQ[output], ExpandFileName@FileNameJoin[{output, FileBaseName[ifname]<>".wl"}],
  True, output
];
If[FileExistsQ[ofname] && Not[force], (
  Message[ExtractCode::exist, ofname];
  Return[$Failed]
)];
Write["stderr", ToString@StringForm["[info]: extracting code from file '``' ... ", ifname]];
UsingFrontEnd[
  With[{nb = NotebookOpen[ifname,Visible->False]}, (
    data = Riffle[NotebookImport[nb, "Input"|"Code"->"InputText"],"\n\n\n"];
    hash = Hash[data];
    NotebookClose[nb];
  )]
];
If[FileExistsQ[ofname] && hash === getHash[ofname],
  Write["stderr", "[hash]: hash is the same"];
  Write["stderr", "[info]: complete"];
  Return[ofname];
];
Write["stderr", ToString@StringForm["[info]: writing to the file '``' ... ", ofname]];
With[{fstream=OpenWrite[ofname]}, (
  WriteString[fstream, ToString[StringForm[headerTemplate, ifname]]];
  WriteString[fstream, ToString[StringForm[dateTemplate, DateString[]]]];
  WriteString[fstream, ToString[StringForm[hashTemplate, hash]]];
  WriteString[fstream,#]&/@data;
  Close[fstream];
)];
Write["stderr", "[info]: complete"];
Return[ofname];
];


parse[] := Which[
  $ScriptCommandLine =!= {}, {Length[#], #}&[$ScriptCommandLine],
  Length[$CommandLine] >= 2 && $CommandLine[[2]] === "-script", {Length[#], #}&[$CommandLine[[3;;]]],
  True, {0, {}}
];


main[] := Module[{argc, argv, result, forceFlag, output=Null},
  {argc, argv} = parse[];
  (* can not parse command-line arguments *)
  If[argc == 0, Return[Null]];
  (* usage message *)
  If[MemberQ[argv, "-h"] || MemberQ[argv, "-help"] || (argc == 1),
    Write["stderr", ExtractCode::usage];
    Write["stderr", ExtractCode::help];
    Exit[0];
  ];
  forceFlag = MemberQ[argv, "-force"];
  If[forceFlag, (
    argv = DeleteCases[argv, "-force"];
    argc -= 1;
  )];
  If[MemberQ[argv, "-o"], (
    With[{pos = First@Flatten@Position[argv, "-o"]},
      output = argv[[pos + 1]];
      argv = Delete[argv, {{pos}, {pos + 1}}];
    ];
  )];
  result = ExtractCode[#, output, "force"->forceFlag]& /@ Rest[argv];
  Exit[Boole[MemberQ[result, $Failed]]];
];


main[]
